name: Continuous Integration

on:
    push:
      branches: [ "master" ]
    pull_request:
      branches: [ "master" ]

jobs:
    coverage_report:
        name: Generate coverage report
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
          with:
            submodules: recursive

        - name: Setup LCOV
          uses: hrishikesh-kadam/setup-lcov@v1

        - name: Run Coverage
          run: ./run-coverage.sh

        - name: Report code coverage
          uses: zgosalvez/github-actions-report-lcov@v3
          with:
            coverage-files: build/coverage/lcov.*.info
            minimum-coverage: 90
            artifact-name: code-coverage-report
            github-token: ${{ secrets.GITHUB_TOKEN }}
            update-comment: true