name: Test on multiple platforms

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build_type: [x64-Release, x64-Debug]
        c_compiler: [gcc, clang,cl]
        include:
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
            build_type: x64-ASan
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
            build_type: x64-Debug-win32
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
            build_type: x64-Release-win32
        exclude:
          - os: macos-latest
            c_compiler: gcc
          - os: macos-latest
            c_compiler: cl
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang


    steps:
    - uses: actions/checkout@v3
    - name: Set VCPKG_ROOT env variable
      shell: bash
      run: |
        echo "VCPKG_ROOT=$(echo $VCPKG_INSTALLATION_ROOT)" >> "$GITHUB_ENV"
    - name: Configure
      run: >
        cmake --preset ${{ matrix.build_type }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}

    - name: Build
      run: cmake --build --preset ${{ matrix.build_type }}

    - name: Test
      run: ctest --preset ${{ matrix.build_type }}

  coverage:
    needs: build
    uses: ./.github/workflows/coverage-report-lcov.yml
