name: Test on multiple platforms

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest]
        build_type: [x86_x64-Release, x86_x64-Debug, x86_x64-ASan]
        c_compiler: [gcc, clang, cl]
        include:
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
          - os: macos-latest
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          # Leak check and other features are not supported on macOS as of Oct 2023
          - os: macos-latest
            build_type: x86_x64-ASan
          - os: macos-latest
            c_compiler: gcc
          - os: macos-latest
            c_compiler: cl
          - os: ubuntu-latest
            c_compiler: cl

    steps:
    - uses: actions/checkout@v3
    - name: Set VCPKG_ROOT env variable
      id: strings
      shell: bash
      run: |
        echo "VCPKG_ROOT=$(echo $VCPKG_INSTALLATION_ROOT)" >> "$GITHUB_ENV"
    - name: Configure
      run: >
        cmake --preset ${{ matrix.build_type }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}

    - name: Build
      run: cmake --build --preset ${{ matrix.build_type }}

    - name: Test
      run: ctest --preset ${{ matrix.build_type }}

  coverage:
    needs: build
    uses: ./.github/workflows/coverage-report-lcov.yml
